version: "3"
services:
  user-db:
    container_name: user-db
    image: postgres:12.3
    ports:
      - 5432:5432
    env_file:
      - ./users/database.env
    volumes:
      - ./users/infra:/docker-entrypoint-initdb.d/
      - db_user:/var/lib/postgresql/data
  product-db:
    container_name: product-db
    image: postgres:12.3
    ports:
      - 5433:5432
    env_file:
      - ./products/database.env
    volumes:
      - ./products/infra:/docker-entrypoint-initdb.d/
      - db_products:/var/lib/postgresql/data
  user-service:
    container_name: user-service
    build:
      context: ./users
      dockerfile: Dockerfile
    image: user-service:0.0.1
    ports:
      - 8485:50001
    env_file:
      - ./users/.env
    depends_on:
      - user-db
  product-service:
    container_name: product-service
    build:
      context: ./products
      dockerfile: Dockerfile
    image: product-service:0.0.1
    ports:
      - 8486:50001
    env_file:
      - ./products/.env
    depends_on:
      - product-db
  discount-calculator-service:
    container_name: discount-calculator-service
    build:
      context: ./discountcalculator
      dockerfile: Dockerfile
    image: discount-calculator-service:0.0.1
    ports:
      - 8487:50001
    env_file:
      - ./discountcalculator/.env
    depends_on:
      - product-service
      - user-service

volumes:
  db_user:
  db_products:
