// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: discountcalculator.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DiscountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DiscountRequest) Reset() {
	*x = DiscountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountcalculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountRequest) ProtoMessage() {}

func (x *DiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discountcalculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountRequest.ProtoReflect.Descriptor instead.
func (*DiscountRequest) Descriptor() ([]byte, []int) {
	return file_discountcalculator_proto_rawDescGZIP(), []int{0}
}

func (x *DiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DiscountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DiscountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Product `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DiscountResponse) Reset() {
	*x = DiscountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountcalculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountResponse) ProtoMessage() {}

func (x *DiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discountcalculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountResponse.ProtoReflect.Descriptor instead.
func (*DiscountResponse) Descriptor() ([]byte, []int) {
	return file_discountcalculator_proto_rawDescGZIP(), []int{1}
}

func (x *DiscountResponse) GetResult() *Product {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_discountcalculator_proto protoreflect.FileDescriptor

var file_discountcalculator_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x72, 0x65, 0x70, 0x6f, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x3e, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x65, 0x70, 0x6f,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x99, 0x01, 0x0a, 0x19, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x65, 0x70,
	0x6f, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x65,
	0x70, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x30, 0x01, 0x42, 0x1e, 0x0a, 0x14,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x61, 0x6d, 0x75, 0x65, 0x6c, 0x73, 0x73, 0x61, 0x6e, 0x74, 0x6f,
	0x73, 0x2e, 0x70, 0x62, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_discountcalculator_proto_rawDescOnce sync.Once
	file_discountcalculator_proto_rawDescData = file_discountcalculator_proto_rawDesc
)

func file_discountcalculator_proto_rawDescGZIP() []byte {
	file_discountcalculator_proto_rawDescOnce.Do(func() {
		file_discountcalculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_discountcalculator_proto_rawDescData)
	})
	return file_discountcalculator_proto_rawDescData
}

var file_discountcalculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discountcalculator_proto_goTypes = []interface{}{
	(*DiscountRequest)(nil),  // 0: protorepo.DiscountRequest
	(*DiscountResponse)(nil), // 1: protorepo.DiscountResponse
	(*Product)(nil),          // 2: protorepo.Product
}
var file_discountcalculator_proto_depIdxs = []int32{
	2, // 0: protorepo.DiscountResponse.result:type_name -> protorepo.Product
	0, // 1: protorepo.DiscountCalculatorService.Process:input_type -> protorepo.DiscountRequest
	0, // 2: protorepo.DiscountCalculatorService.List:input_type -> protorepo.DiscountRequest
	1, // 3: protorepo.DiscountCalculatorService.Process:output_type -> protorepo.DiscountResponse
	2, // 4: protorepo.DiscountCalculatorService.List:output_type -> protorepo.Product
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_discountcalculator_proto_init() }
func file_discountcalculator_proto_init() {
	if File_discountcalculator_proto != nil {
		return
	}
	file_products_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_discountcalculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountcalculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discountcalculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discountcalculator_proto_goTypes,
		DependencyIndexes: file_discountcalculator_proto_depIdxs,
		MessageInfos:      file_discountcalculator_proto_msgTypes,
	}.Build()
	File_discountcalculator_proto = out.File
	file_discountcalculator_proto_rawDesc = nil
	file_discountcalculator_proto_goTypes = nil
	file_discountcalculator_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DiscountCalculatorServiceClient is the client API for DiscountCalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountCalculatorServiceClient interface {
	Process(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountResponse, error)
	List(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (DiscountCalculatorService_ListClient, error)
}

type discountCalculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountCalculatorServiceClient(cc grpc.ClientConnInterface) DiscountCalculatorServiceClient {
	return &discountCalculatorServiceClient{cc}
}

func (c *discountCalculatorServiceClient) Process(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (*DiscountResponse, error) {
	out := new(DiscountResponse)
	err := c.cc.Invoke(ctx, "/protorepo.DiscountCalculatorService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountCalculatorServiceClient) List(ctx context.Context, in *DiscountRequest, opts ...grpc.CallOption) (DiscountCalculatorService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DiscountCalculatorService_serviceDesc.Streams[0], "/protorepo.DiscountCalculatorService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &discountCalculatorServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiscountCalculatorService_ListClient interface {
	Recv() (*Product, error)
	grpc.ClientStream
}

type discountCalculatorServiceListClient struct {
	grpc.ClientStream
}

func (x *discountCalculatorServiceListClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiscountCalculatorServiceServer is the server API for DiscountCalculatorService service.
type DiscountCalculatorServiceServer interface {
	Process(context.Context, *DiscountRequest) (*DiscountResponse, error)
	List(*DiscountRequest, DiscountCalculatorService_ListServer) error
}

// UnimplementedDiscountCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiscountCalculatorServiceServer struct {
}

func (*UnimplementedDiscountCalculatorServiceServer) Process(context.Context, *DiscountRequest) (*DiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (*UnimplementedDiscountCalculatorServiceServer) List(*DiscountRequest, DiscountCalculatorService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterDiscountCalculatorServiceServer(s *grpc.Server, srv DiscountCalculatorServiceServer) {
	s.RegisterService(&_DiscountCalculatorService_serviceDesc, srv)
}

func _DiscountCalculatorService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountCalculatorServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protorepo.DiscountCalculatorService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountCalculatorServiceServer).Process(ctx, req.(*DiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountCalculatorService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiscountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscountCalculatorServiceServer).List(m, &discountCalculatorServiceListServer{stream})
}

type DiscountCalculatorService_ListServer interface {
	Send(*Product) error
	grpc.ServerStream
}

type discountCalculatorServiceListServer struct {
	grpc.ServerStream
}

func (x *discountCalculatorServiceListServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

var _DiscountCalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protorepo.DiscountCalculatorService",
	HandlerType: (*DiscountCalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _DiscountCalculatorService_Process_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _DiscountCalculatorService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "discountcalculator.proto",
}
